// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Sprint1.Data;

#nullable disable

namespace Sprint1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251123154418_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sprint1.Models.Dispositivo", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("UUID");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.HasKey("Uuid");

                    b.ToTable("DISPOSITIVO", (string)null);
                });

            modelBuilder.Entity("Sprint1.Models.Suporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ADMIN_ID");

                    b.Property<DateTime>("DataReclamacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_RECLAMACAO");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_RESOLUCAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TITULO");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SUPORTE", (string)null);
                });

            modelBuilder.Entity("Sprint1.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ALTURA");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<string>("DispositivoId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("DISPOSITIVO_ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("ModeloTrabalho")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MODELO_TRABALHO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("Peso")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("PESO");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ROLE");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SENHA_HASH");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SEXO");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("Sprint1.Models.Suporte", b =>
                {
                    b.HasOne("Sprint1.Models.Usuario", "Atendente")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sprint1.Models.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atendente");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Sprint1.Models.Usuario", b =>
                {
                    b.HasOne("Sprint1.Models.Dispositivo", "Dispositivo")
                        .WithMany()
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");
                });
#pragma warning restore 612, 618
        }
    }
}
